import { Flex, Text, Spacer } from '@chakra-ui/react'
import UserForm from '../components/UserForm'
import CollectionCard from "../components/WebsiteCard"

export default function Home() {
    return (
        <>
        <Flex maxW="1000px" ml="auto" mr="auto" pt="24px" mb="24px">
            <Text fontSize="24px" fontWeight="bold">My Websites</Text>
            <Spacer/>
            <UserForm/>
        </Flex>
        <CollectionCard name={"Mama's Recipes"} desc={"This is the description for my website auto generated by the quick website engine. Here I will put all of my mom’s amazing recipes for the world to see. Enjoy!"} url={"https://www.autogeneratedURL.com"}/>
        <CollectionCard name={"Personal Website"} desc={"This is the description for my website auto generated by the quick website engine. Here I will put all of my mom’s amazing recipes for the world to see. Enjoy!"} url={"https://www.autogeneratedURL.com"}/>
        <CollectionCard name={"NextJS Test"} desc={"This is the description for my website auto generated by the quick website engine. Here I will put all of my mom’s amazing recipes for the world to see. Enjoy!"} url={"https://www.autogeneratedURL.com"}/>
        </>
    )
}